#!/usr/bin/env bash

echo
echo == Push image to ECR
echo

# Login to ECR
eval $(aws ecr get-login --region $ECR_REGION)

docker tag $DOCKER_ACCOUNT/$DOCKER_IMAGE:latest $DOCKER_REPOSITORY/$DOCKER_ACCOUNT/$DOCKER_IMAGE:latest
docker tag $DOCKER_ACCOUNT/$DOCKER_IMAGE:$TAG_PRODUCTION $DOCKER_REPOSITORY/$DOCKER_ACCOUNT/$DOCKER_IMAGE:$TAG_PRODUCTION

# Push built images with all tags
docker push $DOCKER_REPOSITORY/$DOCKER_ACCOUNT/$DOCKER_IMAGE:latest
docker push $DOCKER_REPOSITORY/$DOCKER_ACCOUNT/$DOCKER_IMAGE:$TAG_PRODUCTION

docker rmi $DOCKER_REPOSITORY/$DOCKER_ACCOUNT/$DOCKER_IMAGE:latest $DOCKER_REPOSITORY/$DOCKER_ACCOUNT/$DOCKER_IMAGE:$TAG_PRODUCTION
